



# from RobotArm import RobotArm

# robotArm = RobotArm('exercise 4')

# robotArm.grab()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.drop()

# robotArm.speed = 99999


# robotArm.wait()

#<---------------------------------------- Oefening 4 -->


# from RobotArm import RobotArm

# robotArm = RobotArm('exercise 5')

# # Jouw python instructies zet je vanaf hier:

# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.wait()

# <-------- oefening 5 ------ >

# from RobotArm import RobotArm
# robotArm = RobotArm('exercise 6')

# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()
# robotArm.moveLeft()
# robotArm.grab()
# robotArm.moveLeft()
# robotArm.drop()
# robotArm.moveRight()
# robotArm.grab()
# robotArm.moveRight()
# robotArm.drop()



# robotArm.wait()

# <<------ oefening 6 --->




