naam = input("Voer uw voor en achternaam in: ")
adres = input("Voer uw adres in: ")
postcode = input("Voer uw postcode in: ")
woonplaats = input("Voer uw woonplaats in: ")

print("----------------------------------------------------")
print(f"|  Naam      : {naam}   ")
print(f"|  Adres     : {adres} ")
print(f"|  Postcode  : {postcode}   ")
print(f"|  Woonplaats: {woonplaats}")
print("----------------------------------------------------")